/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.Toolkit;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import login.loginform;
import login.logoutform;
/**
 *
 * @author Kelompok 2
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        jMenuHome.setEnabled(false); 
    }
    
    private void setMenuState(boolean status) {
        jMenuHome.setEnabled(status); 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuHome = new javax.swing.JMenu();
        jMenuMaster = new javax.swing.JMenu();
        jMenuItemBarang = new javax.swing.JMenuItem();
        jMenuItemSupplier = new javax.swing.JMenuItem();
        jMenuItemPelanggan = new javax.swing.JMenuItem();
        jMenuTransaksi = new javax.swing.JMenu();
        jMenuItemPembelian = new javax.swing.JMenuItem();
        jMenuItemPenjualan = new javax.swing.JMenuItem();
        jMenuItemStok = new javax.swing.JMenuItem();
        jMenuReport = new javax.swing.JMenu();
        jMenuItemLaporanBarang = new javax.swing.JMenuItem();
        jMenuItemLaporanPembelian = new javax.swing.JMenuItem();
        jMenuItemLaporanPenjualan = new javax.swing.JMenuItem();
        jMenuItemLaporanStok = new javax.swing.JMenuItem();
        jMenuPengaturan = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemGantiPassword = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("WHAREHOUSE TOKO BESI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 290, 130));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/wharehouse.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1020, 680));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 680));

        jMenuHome.setText("Home");
        jMenuBar1.add(jMenuHome);

        jMenuMaster.setText("Master");

        jMenuItemBarang.setText("Data Barang");
        jMenuItemBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBarangActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemBarang);

        jMenuItemSupplier.setText("Data Supplier");
        jMenuItemSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSupplierActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemSupplier);

        jMenuItemPelanggan.setText("Data Pelanggan");
        jMenuItemPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPelangganActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemPelanggan);

        jMenuBar1.add(jMenuMaster);

        jMenuTransaksi.setText("Transaksi");

        jMenuItemPembelian.setText("Pembelian");
        jMenuItemPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPembelianActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemPembelian);

        jMenuItemPenjualan.setText("Penjualan");
        jMenuItemPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPenjualanActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemPenjualan);

        jMenuItemStok.setText("Stok Barang");
        jMenuItemStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStokActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemStok);

        jMenuBar1.add(jMenuTransaksi);

        jMenuReport.setText("Report");

        jMenuItemLaporanBarang.setText("Laporan Barang");
        jMenuItemLaporanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLaporanBarangActionPerformed(evt);
            }
        });
        jMenuReport.add(jMenuItemLaporanBarang);

        jMenuItemLaporanPembelian.setText("Laporan Pembelian");
        jMenuItemLaporanPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLaporanPembelianActionPerformed(evt);
            }
        });
        jMenuReport.add(jMenuItemLaporanPembelian);

        jMenuItemLaporanPenjualan.setText("Laporan Penjualan");
        jMenuItemLaporanPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLaporanPenjualanActionPerformed(evt);
            }
        });
        jMenuReport.add(jMenuItemLaporanPenjualan);

        jMenuItemLaporanStok.setText("Laporan Stok");
        jMenuItemLaporanStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLaporanStokActionPerformed(evt);
            }
        });
        jMenuReport.add(jMenuItemLaporanStok);

        jMenuBar1.add(jMenuReport);

        jMenuPengaturan.setText("Pengaturan");
        jMenuPengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPengaturanActionPerformed(evt);
            }
        });

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuPengaturan.add(jMenuItemLogout);

        jMenuItemGantiPassword.setText("Ganti Password");
        jMenuItemGantiPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGantiPasswordActionPerformed(evt);
            }
        });
        jMenuPengaturan.add(jMenuItemGantiPassword);

        jMenuBar1.add(jMenuPengaturan);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jMenuItemBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBarangActionPerformed
        DataBarang dataBarang = new DataBarang(); // Membuat objek halaman Data Barang
        dataBarang.setVisible(true); // Menampilkan halaman Data Barang
        dataBarang.setLocationRelativeTo(null); // Memposisikan halaman di tengah layar
    }//GEN-LAST:event_jMenuItemBarangActionPerformed

    private void jMenuItemSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSupplierActionPerformed
        DataSupplier datasupplier = new DataSupplier();
        datasupplier.setVisible(true);
        datasupplier.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemSupplierActionPerformed

    private void jMenuItemPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPenjualanActionPerformed
        PenjualanForm penjualanform = new PenjualanForm();
        penjualanform.setVisible(true);
        penjualanform.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemPenjualanActionPerformed

    private void jMenuItemLaporanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLaporanBarangActionPerformed
        LaporanBarangForm laporanbarangform = new LaporanBarangForm();
        laporanbarangform.setVisible(true);
        laporanbarangform.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemLaporanBarangActionPerformed

    private void jMenuItemLaporanPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLaporanPembelianActionPerformed
        LaporanPembelianForm laporanpembelianform = new LaporanPembelianForm();
        laporanpembelianform.setVisible(true);
        laporanpembelianform.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemLaporanPembelianActionPerformed

    private void jMenuItemLaporanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLaporanPenjualanActionPerformed
        LaporanPenjualanForm laporanPenjualanform = new LaporanPenjualanForm();
        laporanPenjualanform.setVisible(true);
        laporanPenjualanform.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemLaporanPenjualanActionPerformed

    private void jMenuPengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPengaturanActionPerformed

    }//GEN-LAST:event_jMenuPengaturanActionPerformed

    private void jMenuItemGantiPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGantiPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemGantiPasswordActionPerformed

    private void jMenuItemPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPelangganActionPerformed
        DataPelanggan datapelanggan = new DataPelanggan();
        datapelanggan.setVisible(true);
        datapelanggan.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemPelangganActionPerformed

    private void jMenuItemPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPembelianActionPerformed
        PembelianForm pembelianform = new PembelianForm();
        pembelianform.setVisible(true);
        pembelianform.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemPembelianActionPerformed

    private void jMenuItemStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStokActionPerformed
        StokForm stokform = new StokForm();
        stokform.setVisible(true);
        stokform.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemStokActionPerformed

    private void jMenuItemLaporanStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLaporanStokActionPerformed
        LaporanStokForm laporanstokform = new LaporanStokForm();
        laporanstokform.setVisible(true);
        laporanstokform.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemLaporanStokActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        logoutform logoutform = new logoutform();
        logoutform.setVisible(true);
        logoutform.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHome;
    private javax.swing.JMenuItem jMenuItemBarang;
    private javax.swing.JMenuItem jMenuItemGantiPassword;
    private javax.swing.JMenuItem jMenuItemLaporanBarang;
    private javax.swing.JMenuItem jMenuItemLaporanPembelian;
    private javax.swing.JMenuItem jMenuItemLaporanPenjualan;
    private javax.swing.JMenuItem jMenuItemLaporanStok;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemPelanggan;
    private javax.swing.JMenuItem jMenuItemPembelian;
    private javax.swing.JMenuItem jMenuItemPenjualan;
    private javax.swing.JMenuItem jMenuItemStok;
    private javax.swing.JMenuItem jMenuItemSupplier;
    private javax.swing.JMenu jMenuMaster;
    private javax.swing.JMenu jMenuPengaturan;
    private javax.swing.JMenu jMenuReport;
    private javax.swing.JMenu jMenuTransaksi;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
