/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.Toolkit;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import login.loginform;
import login.logoutform;
/**
 *
 * @author Kelompok 2
 */ 
public class MainMenu extends javax.swing.JFrame {
 
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        jMenuHome.setEnabled(false); 
    }
    
    private void setMenuState(boolean status) {
        jMenuHome.setEnabled(status); 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuHome = new javax.swing.JMenu();
        jMenuMaster = new javax.swing.JMenu();
        jMenuItemBarang = new javax.swing.JMenuItem();
        jMenuItemSupplier = new javax.swing.JMenuItem();
        jMenuItemPelanggan = new javax.swing.JMenuItem();
        jMenuTransaksi = new javax.swing.JMenu();
        jMenuItemPembelian = new javax.swing.JMenuItem();
        jMenuItemPenjualan = new javax.swing.JMenuItem();
        jMenuItemStok = new javax.swing.JMenuItem();
        jMenuPengaturan = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rekapitulasi Barang Jakarta Besi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 640, 120));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/wharehouse.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1290, 680));

        jMenuHome.setText("Home");
        jMenuBar1.add(jMenuHome);

        jMenuMaster.setText("Master");

        jMenuItemBarang.setText("Data Barang");
        jMenuItemBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBarangActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemBarang);

        jMenuItemSupplier.setText("Data Supplier");
        jMenuItemSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSupplierActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemSupplier);

        jMenuItemPelanggan.setText("Data Pelanggan");
        jMenuItemPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPelangganActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemPelanggan);

        jMenuBar1.add(jMenuMaster);

        jMenuTransaksi.setText("Transaksi");

        jMenuItemPembelian.setText("Mitra");
        jMenuItemPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPembelianActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemPembelian);

        jMenuItemPenjualan.setText("Penjualan");
        jMenuItemPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPenjualanActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemPenjualan);

        jMenuItemStok.setText("Stok Barang");
        jMenuItemStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStokActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemStok);

        jMenuBar1.add(jMenuTransaksi);

        jMenuPengaturan.setText("Pengaturan");
        jMenuPengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPengaturanActionPerformed(evt);
            }
        });

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuPengaturan.add(jMenuItemLogout);

        jMenuBar1.add(jMenuPengaturan);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jMenuItemBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBarangActionPerformed
        DataBarang dataBarang = new DataBarang(); // Membuat objek halaman Data Barang
        dataBarang.setVisible(true); // Menampilkan halaman Data Barang
        dataBarang.setLocationRelativeTo(null); // Memposisikan halaman di tengah layar
    }//GEN-LAST:event_jMenuItemBarangActionPerformed

    private void jMenuItemSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSupplierActionPerformed
        DataSupplier datasupplier = new DataSupplier();
        datasupplier.setVisible(true);
        datasupplier.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemSupplierActionPerformed

    private void jMenuItemPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPenjualanActionPerformed
        PenjualanForm penjualanform = new PenjualanForm();
        penjualanform.setVisible(true);
        penjualanform.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemPenjualanActionPerformed

    private void jMenuPengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPengaturanActionPerformed

    }//GEN-LAST:event_jMenuPengaturanActionPerformed

    private void jMenuItemPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPelangganActionPerformed
        DataPelanggan datapelanggan = new DataPelanggan();
        datapelanggan.setVisible(true);
        datapelanggan.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemPelangganActionPerformed

    private void jMenuItemPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPembelianActionPerformed
        MitraPembelianForm pembelianform = new MitraPembelianForm();
        pembelianform.setVisible(true);
        pembelianform.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemPembelianActionPerformed

    private void jMenuItemStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStokActionPerformed
        StokForm stokform = new StokForm();
        stokform.setVisible(true);
        stokform.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemStokActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        logoutform logoutform = new logoutform();
        logoutform.setVisible(true);
        logoutform.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    public void setAksesMenu(String role) {
        if (role.equals("admin")) {
            // Semua menu aktif
            jMenuMaster.setVisible(true);
            jMenuTransaksi.setVisible(true);
            jMenuPengaturan.setVisible(true);

            jMenuItemBarang.setVisible(true);
            jMenuItemSupplier.setVisible(true);
            jMenuItemPelanggan.setVisible(true);
            jMenuItemPembelian.setVisible(true);
            jMenuItemPenjualan.setVisible(true);
            jMenuItemStok.setVisible(true);

        } else if (role.equals("kasir")) {
            // Kasir hanya bisa penjualan
            jMenuMaster.setVisible(false);
            jMenuTransaksi.setVisible(true);
            jMenuPengaturan.setVisible(true);

            jMenuItemPembelian.setVisible(false);  // Mitra
            jMenuItemStok.setVisible(false);       // Stok Barang
            jMenuItemPenjualan.setVisible(true);   // Penjualan

        } else if (role.equals("gudang")) {
            // Gudang tidak bisa penjualan & pelanggan
            jMenuMaster.setVisible(true);
            jMenuTransaksi.setVisible(true);
            jMenuPengaturan.setVisible(true);

            jMenuItemBarang.setVisible(true);
            jMenuItemSupplier.setVisible(true);
            jMenuItemPelanggan.setVisible(false);  // tidak boleh

            jMenuItemPembelian.setVisible(true);   // Mitra
            jMenuItemStok.setVisible(true);        // Stok Barang
            jMenuItemPenjualan.setVisible(false);  // tidak boleh
        }
    }


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHome;
    private javax.swing.JMenuItem jMenuItemBarang;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemPelanggan;
    private javax.swing.JMenuItem jMenuItemPembelian;
    private javax.swing.JMenuItem jMenuItemPenjualan;
    private javax.swing.JMenuItem jMenuItemStok;
    private javax.swing.JMenuItem jMenuItemSupplier;
    private javax.swing.JMenu jMenuMaster;
    private javax.swing.JMenu jMenuPengaturan;
    private javax.swing.JMenu jMenuTransaksi;
    // End of variables declaration//GEN-END:variables
}
