/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import koneksi.koneksidatabase;
import model.Mitra;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;  
import javax.swing.ListSelectionModel;       
import java.text.DecimalFormat;  
/**
 *
 * @author Kelompok 2
 */
public class MitraPembelianForm extends javax.swing.JFrame {

    /**
     * Creates new form PembelianForm
     */
    public MitraPembelianForm() {
        initComponents();
        refreshTable();
        loadDataPelanggan();
        loadDataBarang();
        hitungTotalHarga(); // Hitung di awal jika field sudah terisi

        txtJumlah.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                hitungTotalHarga();
            }
        });

        txtHargaSatuan.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                hitungTotalHarga();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNamaMitra = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtHargaSatuan = new javax.swing.JTextField();
        totalHarga = new javax.swing.JTextField();
        cmbSupplier = new javax.swing.JComboBox<>();
        cmbBarang = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        namaBarangTxt = new javax.swing.JTextField();
        tambahPembelianBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPembelian = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(70, 130, 180));
        jPanel1.setPreferredSize(new java.awt.Dimension(821, 544));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MITRA");

        jLabel2.setText("Nama Mitra");

        jLabel3.setText("Kode Supplier");

        jLabel4.setText("Kode Barang");

        jLabel5.setText("Jumlah");

        jLabel6.setText("Harga Satuan");

        jLabel7.setText("Total");

        txtNamaMitra.setEditable(false);
        txtNamaMitra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMitraActionPerformed(evt);
            }
        });

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        txtHargaSatuan.setEditable(false);
        txtHargaSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaSatuanActionPerformed(evt);
            }
        });

        totalHarga.setEditable(false);
        totalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalHargaActionPerformed(evt);
            }
        });

        cmbSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSupplierActionPerformed(evt);
            }
        });

        cmbBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBarangActionPerformed(evt);
            }
        });

        jLabel8.setText("Nama Barang");

        namaBarangTxt.setEditable(false);
        namaBarangTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        namaBarangTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaBarangTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNamaMitra, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(cmbSupplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaBarangTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 466, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(txtNamaMitra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(totalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cmbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(namaBarangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        tambahPembelianBtn.setText("Tambah");
        tambahPembelianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPembelianBtnActionPerformed(evt);
            }
        });

        jPanel3.setPreferredSize(new java.awt.Dimension(791, 61));

        jLabel9.setText("Cari Transaksi");

        jButton4.setText("Cari");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(59, 59, 59))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(484, 155));

        tabelPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pembelian", "Kode Supplier", "Nama Mitra", "Kode Barang", "Jumlah", "Harga", "Total", "Tanggal"
            }
        ));
        tabelPembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPembelianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPembelian);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton5.setText("X");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1103, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1103, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(508, 508, 508)
                .addComponent(tambahPembelianBtn)
                .addContainerGap(544, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tambahPembelianBtn)
                .addGap(9, 9, 9)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1123, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean tambahPembelian(Mitra m) {
        String sql = "INSERT INTO mitra (kode_supplier, nama_mitra, kode_barang, jumlah, harga_satuan, total_harga, tanggal) VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)";

        try (Connection conn = koneksidatabase.getConnection();
             PreparedStatement pst = conn.prepareStatement(sql)) {

            pst.setString(1, m.getKodeSupplier());
            pst.setString(2, m.getNamaMitra());
            pst.setString(3, m.getKodeBarang());
            pst.setInt(4, m.getJumlah());
            pst.setDouble(5, m.getHargaSatuan());
            pst.setDouble(6, m.getTotalHarga());

            return pst.executeUpdate() > 0;

        } catch (SQLException e) {
            System.err.println("Gagal Tambah Pembelian: " + e.getMessage());
            return false;
        }
    }
    

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tambahPembelianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPembelianBtnActionPerformed
        String kodeSupplier = cmbSupplier.getSelectedItem().toString();
        String namaMitra = txtNamaMitra.getText();
        String kodeBarang = cmbBarang.getSelectedItem().toString();
        int jumlah = Integer.parseInt(txtJumlah.getText());
        double hargaSatuan = Double.parseDouble(txtHargaSatuan.getText());
        double totalHarga = jumlah * hargaSatuan;

        Mitra m = new Mitra(kodeSupplier, namaMitra, kodeBarang, jumlah, hargaSatuan, totalHarga);

        if (tambahPembelian(m)) {
            JOptionPane.showMessageDialog(null, "Pembelian berhasil disimpan!");
            clearForm();
            refreshTable();
        }
    }//GEN-LAST:event_tambahPembelianBtnActionPerformed

    private void tabelPembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPembelianMouseClicked
        // Todo Kalo ada edit
    }//GEN-LAST:event_tabelPembelianMouseClicked

    private void cmbSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSupplierActionPerformed
        String kode = (String) cmbSupplier.getSelectedItem();
        if (kode != null && !kode.equals("-- Pilih Kode --")) {
            try {
                Connection conn = koneksidatabase.getConnection();
                PreparedStatement ps = conn.prepareStatement(
                    "SELECT nama_supplier FROM supplier WHERE kode_supplier = ?"
                );
                ps.setString(1, kode);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    txtNamaMitra.setText(rs.getString("nama_supplier"));
                } else {
                    txtNamaMitra.setText("");                    
                }
                
                rs.close();
                ps.close();
                conn.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal ambil barang: " + e.getMessage());
            }
        } else {
            txtNamaMitra.setText("");
        }
    }//GEN-LAST:event_cmbSupplierActionPerformed

    private void cmbBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBarangActionPerformed
        String kode = (String) cmbBarang.getSelectedItem();
        if (kode != null && !kode.equals("-- Pilih Kode --")) {
            try {
                Connection conn = koneksidatabase.getConnection();
                PreparedStatement ps = conn.prepareStatement(
                    "SELECT nama_barang, harga FROM barang WHERE kode_barang = ?"
                );
                ps.setString(1, kode);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    namaBarangTxt.setText(rs.getString("nama_barang"));
                    txtHargaSatuan.setText(String.valueOf(rs.getDouble("harga"))); // atau rs.getString("harga")
                } else {
                    namaBarangTxt.setText("");
                    txtHargaSatuan.setText("");
                    
                }
                
                rs.close();
                ps.close();
                conn.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal ambil barang: " + e.getMessage());
            }
        } else {
            namaBarangTxt.setText("");
            txtHargaSatuan.setText("");
        }
    }//GEN-LAST:event_cmbBarangActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtHargaSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaSatuanActionPerformed

    }//GEN-LAST:event_txtHargaSatuanActionPerformed

    private void namaBarangTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaBarangTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaBarangTxtActionPerformed

    private void totalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalHargaActionPerformed

    private void txtNamaMitraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMitraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMitraActionPerformed

    
    private void loadDataBarang() {
        try {
            Connection conn = koneksidatabase.getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT kode_barang FROM barang");

            cmbBarang.removeAllItems();
            cmbBarang.addItem("-- Pilih Kode --");
            while (rs.next()) {
                cmbBarang.addItem(rs.getString("kode_barang"));
            }
            rs.close();
            st.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load barang: " + e.getMessage());
        }
    }   

    
    
     private void loadDataPelanggan() {
        try {
            Connection conn = koneksidatabase.getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT kode_supplier FROM supplier");

            cmbSupplier.removeAllItems();
            cmbSupplier.addItem("-- Pilih Kode --");
            while (rs.next()) {
               
                cmbSupplier.addItem(rs.getString("kode_supplier"));
            }

            rs.close();
            st.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load supplier: " + e.getMessage());
        }
    }
     
     
     
    
    private void clearForm() {
        cmbSupplier.setSelectedIndex(0);
        txtNamaMitra.setText("");
        cmbBarang.setSelectedIndex(0);
        txtJumlah.setText("");
        txtHargaSatuan.setText("");
        totalHarga.setText("");
    }

    public List<Mitra> getAllPembelian() {
        List<Mitra> list = new ArrayList<>();
        String sql = "SELECT * FROM mitra";

        try (Connection conn = koneksidatabase.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                list.add(new Mitra(
                    rs.getInt("id_pembelian"),
                    rs.getString("kode_supplier"),
                    rs.getString("nama_mitra"),
                    rs.getString("kode_barang"),
                    rs.getInt("jumlah"),
                    rs.getDouble("harga_satuan"),
                    rs.getDouble("total_harga"),
                    rs.getTimestamp("tanggal")
                ));
            }

        } catch (SQLException e) {
            System.err.println("Gagal Mengambil Data Pembelian: " + e.getMessage());
        }

        return list;
    }

    private void loadDataToTable() {
        List<Mitra> list = getAllPembelian();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Kode Supplier");
        model.addColumn("Nama Mitra");
        model.addColumn("Kode Barang");
        model.addColumn("Jumlah");
        model.addColumn("Harga Satuan");
        model.addColumn("Total Harga");
        model.addColumn("Tanggal");

        for (Mitra m : list) {
            model.addRow(new Object[] {
                m.getIdPembelian(), m.getKodeSupplier(), m.getNamaMitra(), m.getKodeBarang(), m.getJumlah(),
                m.getHargaSatuan(), m.getTotalHarga(), m.getTanggal()
            });
        }

        tabelPembelian.setModel(model);
        setColumnWidths();
    }

    private void setColumnWidths() {
        tabelPembelian.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabelPembelian.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabelPembelian.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabelPembelian.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabelPembelian.getColumnModel().getColumn(4).setPreferredWidth(70);
        tabelPembelian.getColumnModel().getColumn(5).setPreferredWidth(100);
        tabelPembelian.getColumnModel().getColumn(6).setPreferredWidth(100);
        tabelPembelian.getColumnModel().getColumn(7).setPreferredWidth(150);
    }

    private void refreshTable() {
        loadDataToTable();
    }

    private void hitungTotalHarga() {
        try {
            int jumlah = Integer.parseInt(txtJumlah.getText().trim());
            double harga = Double.parseDouble(txtHargaSatuan.getText().trim());
            double total = jumlah * harga;

            totalHarga.setText(String.format("%.1f", total));
        } catch (NumberFormatException e) {
            totalHarga.setText("0");
        }
    }
    
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MitraPembelianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MitraPembelianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MitraPembelianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MitraPembelianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MitraPembelianForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbBarang;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField namaBarangTxt;
    private javax.swing.JTable tabelPembelian;
    private javax.swing.JButton tambahPembelianBtn;
    private javax.swing.JTextField totalHarga;
    private javax.swing.JTextField txtHargaSatuan;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNamaMitra;
    // End of variables declaration//GEN-END:variables
}
